import React from "react";
import Image from "next/image";
import Head from "next/head";
import { Icon } from "@iconify/react";
import {
  IntroContent,
  AboutUs,
  Ads,
  Expertise,
  Objectives,
  Services,
  Partners,
  Blog,
  Newsletter,
  Events,
} from "@/components/Home";
import Header from "@/components/header";
import Footer from "@/components/footer";
import UseShowTopBtn from "@/utils/useShowTopBtn";

export default function Home() {
  const [showTopBtn, setShowTopBtn] = UseShowTopBtn();

  return (
    <>
      <Head>
        <title>Cyberroot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <IntroContent />
        <section className="py-10 w-[92%] max-w-[1500px] mx-auto space-y-6">
          <h3 className="capitalize text-3xl font-bold">upcoming events</h3>
          {ExampleEvents()}
          <h3 className="capitalize text-3xl font-bold">past events</h3>
          {ExampleEvents()}
        </section>
        <Footer />
      </main>
    </>
  );
}
function ExampleEvents() {
  return (
    <>
      <div className="flex gap-10 [&>*:nth-child(1)]:w-[40%] [&>*:nth-child(2)]:flex-1">
        <div className="bg-summit-bg rounded-md overflow-hidden text-white bg-no-repeat bg-cover text-left py-10 px-5">
          <h5 className="uppercase font-bold text-2xl">cybersummit 2023</h5>
          <h6 className="text-lg">10-09-2023</h6>
          <p className="text-sm max-w-[280px] py-7">
            Small businesses are often targets for cyber-attacks because they
            are perceived as easy targets. A cybersecurity event designed for
            small business owners and employees can cover topics like risk
            management,
          </p>
          <button className="border border-white text-base rounded-lg px-2 py-1">
            Register for free
          </button>
        </div>
        <div className="bg-demo-summit-bg1 rounded-md overflow-hidden text-white bg-no-repeat bg-cover text-left py-10 px-5">
          <h5 className="uppercase font-bold text-2xl">cybersummit 2023</h5>
          <h6 className="text-lg">10-09-2023</h6>
          <p className="text-sm max-w-[280px] py-7">
            Small businesses are often targets for cyber-attacks because they
            are perceived as easy targets. A cybersecurity event designed for
            small business owners and employees can cover topics like risk
            management,
          </p>
          <button className="border border-white text-base rounded-lg px-2 py-1">
            Register for free
          </button>
        </div>
      </div>
      <div className="flex gap-10 [&>*:nth-child(2)]:w-[40%] [&>*:nth-child(1)]:flex-1">
        <div className="bg-demo-summit-bg2 rounded-md overflow-hidden text-white bg-no-repeat bg-cover text-left py-10 px-5">
          <h5 className="uppercase font-bold text-2xl">cybersummit 2023</h5>
          <h6 className="text-lg">10-09-2023</h6>
          <p className="text-sm max-w-[280px] py-7">
            Small businesses are often targets for cyber-attacks because they
            are perceived as easy targets. A cybersecurity event designed for
            small business owners and employees can cover topics like risk
            management,
          </p>
          <button className="border border-white text-base rounded-lg px-2 py-1">
            Register for free
          </button>
        </div>
        <div className="bg-demo-summit-bg3 rounded-md overflow-hidden text-white bg-no-repeat bg-cover text-left py-10 px-5">
          <h5 className="uppercase font-bold text-2xl">cybersummit 2023</h5>
          <h6 className="text-lg">10-09-2023</h6>
          <p className="text-sm max-w-[280px] py-7">
            Small businesses are often targets for cyber-attacks because they
            are perceived as easy targets. A cybersecurity event designed for
            small business owners and employees can cover topics like risk
            management,
          </p>
          <button className="border border-white text-base rounded-lg px-2 py-1">
            Register for free
          </button>
        </div>
      </div>
    </>
  );
}
